# This is a basic workflow to help you get started with Actions

name: Deploy stuff to MARC Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# stuff remarked out by dave cos this isn't a node.js project yet so compiling it as node would cause errors
jobs:
  # This workflow contains a single job called "build"
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install express sequelize sqlite3 body-parser cors --save
      shell: bash
      working-directory: dist
      
    - name: Run Unit Tests
      run: npm run test --if-present
#    - name: Run build task
#      run: npm run build --if-present

# THIS IS SO SSH-DEPLOY IS DISABLED. 
#    - name: Deploy to Server
#      uses: easingthemes/ssh-deploy@v2.1.6

      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
