# MARC unit tests and integration tests. 
# ---------------------------
# This is executed BY GITHUB. NOT ON OUR LOCAL MACHINES
# ---------------------------
defaults:
  run:
    working-directory: ./src # we have a dist directory. our nodejs program isn't in the root of the project. ./src is where package.json can be found.


name: Deploy stuff to MARC Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# stuff remarked out by dave cos this isn't a node.js project yet so compiling it as node would cause errors
jobs:
  # This workflow contains a single job called "build"
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    #- name: Install npm dependencies
    #  run: npm install express sequelize sqlite3 body-parser cors express-fileupload --save && npm install mocha supertest config --save-dev 
    #  shell: bash

      
    #- name: Run Unit Tests
    #  run: npm run test --if-present
#    - name: Run build task
#      run: npm run build --if-present


